jx:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: jx
    username: root
    password: 2004106
  alioss:
    access-key-id: LTAI5tM91v4vu8vcDnBTYn9u
    access-key-secret: mXIJpPxmnVFRmn9UpNlREaf8u5zyPT
    bucket-name: sky-take-out-acj
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: jx
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: jx
    user-token-name: authentication
    user-ttl: 7200000

